
DIRSDL=/users/prog1a/C/librairie/2011
CFLAGS=-c -g -O2 -I$(DIRSDL)/include/SDL -I$(DIRSDL)/include
LFLAGS=-L$(DIRSDL)/lib -lSDLmain -lSDL -lSDL_ttf -lSDL_image  -lSDL_sound -lSDL_phelma -lSDL_draw -lm

all : expression1 expression2 expression3

expression3 : expression3.o fonctions.o arbre.o traceexp.o
	gcc -o expression3 expression3.o fonctions.o arbre.o traceexp.o  $(LFLAGS)

expression2 : expression2.o fonctions.o arbre.o traceexp.o
	gcc -o expression2 expression2.o fonctions.o arbre.o traceexp.o  $(LFLAGS)

expression1 : expression1.o fonctions.o arbre.o traceexp.o
	gcc -o expression1 expression1.o fonctions.o arbre.o traceexp.o  $(LFLAGS)

expression : expression.o fonctions.o arbre.o traceexp.o 
	gcc -o expression expression.o fonctions.o arbre.o traceexp.o $(LFLAGS)

fonctions.o : fonctions.c
	gcc $(CFLAGS) fonctions.c

arbre.o : arbre.c
	gcc $(CFLAGS) arbre.c

expression3.o : expression3.c
	gcc $(CFLAGS) expression3.c

expression2.o : expression2.c
	gcc $(CFLAGS) expression2.c

expression1.o : expression1.c
	gcc $(CFLAGS) expression1.c

expression.o : expression.c
	gcc $(CFLAGS) expression.c

traceexp.o : traceexp.c
	gcc $(CFLAGS) traceexp.c

